# Generated by Django 5.0.6 on 2024-05-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='/path/to/default/profile_photo.jpg', upload_to='', verbose_name='Photo de profil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CREATOR', 'Créateur'), ('SUBSCRIBER', 'Abonné')], default='/path/to/default/profile_photo.jpg', max_length=30, verbose_name='Rôle'),
            preserve_default=False,
        ),
    ]
